version: "3"

services:
  rust-server:
    container_name: rust-server
    build:
      context: ./
      dockerfile: dev.dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./server:/dev/server/
      - ./client:/dev/client/
    networks:
      - my_network

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=colorful-user
      - MONGO_INITDB_ROOT_PASSWORD=IaascUtcaA%44
    networks:
      - my_network

networks:
  my_network:
    external: true
