version: "3"

services:
  rust-server:
    container_name: rust-server
    build:
      context: ./
      dockerfile: dockerfile
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./sites:/app/sites/
      - ./assets:/app/assets/
    networks:
      - my_network

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_DATABASE=colorful
      - MONGO_INITDB_ROOT_USERNAME=color-user
      - MONGO_INITDB_ROOT_PASSWORD=secretpw
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init.mongo.js:ro
      - ./mongo-volume:/data/db
    networks:
      - my_network
    ports:
      - 27017:27017

networks:
  my_network:
    external: true
