version: "1"

services:
  rust-server:
    container_name: rust-server
    build:
      context: ./rust-server
      dockerfile: ./rust-server/dockerfile
    restart: always
    ports:
      - 443:3000
    networks:
      - my_network

  mongodb:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=colourful-user
      - MONGO_INITDB_ROOT_PASSWORD=IaascUtcaA%44
    networks:
      - my_network

networks:
  my_network:
    external: true
